Job_parser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scraping.urls')),
    path('users/', include('users.urls', namespace='users')),
    path("api/", include("scraping_api.urls")),
    path("api-auth/", include("rest_framework.urls")),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body class="d-flex flex-column min-vh-100">
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Вакансии python, всего {{ job_count }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

                {% if user.is_authenticated %}
                    {% comment %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'users-profile' %}"><img
                            class="rounded-circle" width="30" src="{{ user.profile.avatar.url }}"/> {{ user.username }}
                    </a></li>
                    {% endcomment %}
                    <li class="nav-item">
                        <a class="btn btn-outline-light nav-link" href="{% url 'favorite-vacancy' %}">Избранное</a>
                    </li>
                    <li class="nav-item">
                        <form method="post" action="{% url 'users:logout' %}">{% csrf_token %}
                            <button type="submit">Выйти</button>
                        </form>

                    </li>

                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Log In</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}">Register</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<!-- Page content-->
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="container d-flex align-items-center justify-content-center">
                        <div class="alert alert-warning alert-dismissible fade show w-50  d-block" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}
        </div>
        <!-- Widgets-->
        <div class="col-lg-4">


        </div>
    </div>
</div>
<!-- Footer-->
<footer class="py-5 bg-dark mt-2 mt-auto">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Job parser 2024, Powered by
        Django</p></div>
</footer>
</body>
</html>

templates/pagination.html
<nav aria-label="Pagination">
  <ul class="pagination">
    {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}">Предыдущая</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link">Предыдущая</a>
      </li>
    {% endif %}

    {% with offset=2 %}
      {% if page.number >= offset %}
        <li class="page-item">
          <a class="page-link" href="?page=1">1</a>
        </li>
        {% if page.number > offset %}
          <li class="page-item disabled">
            <a class="page-link">&hellip;</a>
          </li>
        {% endif %}
      {% endif %}

      {% for page_num in page.paginator.page_range %}
        {% if page.number == page_num %}
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% elif page.number >= page_num|add:-2 and page.number <= page_num|add:2 %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page.number <= page.paginator.num_pages|add:"-offset" %}
        {% if page.number < page.paginator.num_pages|add:"-offset" %}
          <li class="page-item disabled">
            <a class="page-link">&hellip;</a>
          </li>
        {% endif %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a>
        </li>
      {% endif %}
    {% endwith %}

    {% if page.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}">Следующая</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link">Следующая</a>
      </li>
    {% endif %}
  </ul>
</nav>